# Site

title: "Speak SQL to your Database [from R]"
handouts:
tag: v0.0
lesson: 0
instructor: Mary Shelley
authors:
 - Mary Shelley

# Slides

slide_sorter:
  - all.md

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.2/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
